# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to the Brain of the BH!
email: bountyhunter19019@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Find out what is going on around you in the world! 
  Learn about water problems around the world, women empowerment, problems around the world and much more. 
  Discuss new subjects every week and give your opinions and ideas about that subject openly.
  Discover the Brain Of The BH!
baseurl: "" # the subpath of your site, e.g. /blog
url: "brainofthebh.github.io" # the base hostname & protocol for your site
github_username:  BrainOfTheBH

# Build settings
markdown: kramdown
